// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-IfEgrPcSDE4owha8wPrfFISvU7JHIus',
    appId: '1:971230238930:web:4f8fd771aa0c08f30cb50b',
    messagingSenderId: '971230238930',
    projectId: 'smart-mart-856e4',
    authDomain: 'smart-mart-856e4.firebaseapp.com',
    storageBucket: 'smart-mart-856e4.firebasestorage.app',
    measurementId: 'G-E632PRHWKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtlGkMywUh4ExXsP3KqV617InwAnbW0wc',
    appId: '1:971230238930:android:74110e296738f8620cb50b',
    messagingSenderId: '971230238930',
    projectId: 'smart-mart-856e4',
    storageBucket: 'smart-mart-856e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTowU65z5MYS8MGxXLBLfCIX6eVxxNRus',
    appId: '1:971230238930:ios:a328341eee5e88180cb50b',
    messagingSenderId: '971230238930',
    projectId: 'smart-mart-856e4',
    storageBucket: 'smart-mart-856e4.firebasestorage.app',
    iosBundleId: 'com.example.smartMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTowU65z5MYS8MGxXLBLfCIX6eVxxNRus',
    appId: '1:971230238930:ios:a328341eee5e88180cb50b',
    messagingSenderId: '971230238930',
    projectId: 'smart-mart-856e4',
    storageBucket: 'smart-mart-856e4.firebasestorage.app',
    iosBundleId: 'com.example.smartMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-IfEgrPcSDE4owha8wPrfFISvU7JHIus',
    appId: '1:971230238930:web:904a7925dfba695c0cb50b',
    messagingSenderId: '971230238930',
    projectId: 'smart-mart-856e4',
    authDomain: 'smart-mart-856e4.firebaseapp.com',
    storageBucket: 'smart-mart-856e4.firebasestorage.app',
    measurementId: 'G-Q4975JEQJK',
  );
}
